apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-calc
  labels:
    app: go-calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-calc
  template:
    metadata:
      labels:
        app: go-calc
    spec:
      containers:
      - name: go-calc
        image: kavighule6/gocalc
        ports:
        - containerPort: 8080
