apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-calc.fullname" . }}
  labels:
    app: {{ include "go-calc.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "go-calc.name" . }}
