
replicaCount: 1

image:
  repository: kavighule6/gocalc
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "01"

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

autoscaling:
  enabled: false

podAnnotations: {}

podLabels: {}
