apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-gocalc-restrictions
spec:
  podSelector:
    matchLabels:
      app: mysql   # Label for MySQL pods
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
